services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    environment:
      ServerIP: '10.0.0.172'
      TZ: 'America/Toronto'
      WEBPASSWORD: 'admin123'
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /volume2/docker/PiHole/pihole/etc-pihole:/etc/pihole
      - /volume2/docker/PiHole/pihole/etc-dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped